#!/bin/bash
# Usage:
#   videotogif source.mp4 > out.gif
#   cat source.mp4 | videotogif > out.gif
input="$1"
test "$input" || input="pipe:0"

ffmpeg -i "$input" -r 10 -f image2pipe -vcodec ppm - \
  | convert -layers Optimize - gif:- \
  | gifsicle -O3 --multifile -
